#index:
#    path: /
#    controller: App\Controller\DefaultController::index
redirect_login:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: login
